In [2]:
import numpy as np

n_samples = 10
k = 5

matrix = np.random.rand(n_samples, k)
row_sums = np.sum(matrix, axis=1)
normalized_matrix = matrix / row_sums[:, np.newaxis]


array([[0.91895806, 0.39064997, 0.64903881, 0.58083675, 0.62168657],
       [0.81694584, 0.82857455, 0.17499012, 0.16897634, 0.09469282],
       [0.76098782, 0.39032137, 0.88907084, 0.43204339, 0.26595682],
       [0.27517449, 0.14101109, 0.8640421 , 0.17380861, 0.10696349],
       [0.68389558, 0.04718907, 0.98738597, 0.86600252, 0.78389681],
       [0.26007164, 0.98002135, 0.59715043, 0.30951071, 0.07713576],
       [0.33116775, 0.18825672, 0.8321146 , 0.74762831, 0.00890571],
       [0.31695213, 0.60343047, 0.81512411, 0.83326136, 0.14775863],
       [0.99632453, 0.26358066, 0.71200172, 0.82537427, 0.14730583],
       [0.83151863, 0.35591229, 0.64027488, 0.38411622, 0.59361059]])

In [1]:
import numpy as np
np.random.seed(0)
matrix = np.random.rand(5, 3)
row_sums = np.sum(matrix, axis=1)
U = matrix / row_sums[:, np.newaxis]
U

array([[0.29399155, 0.38311672, 0.32289173],
       [0.33750765, 0.26241723, 0.40007512],
       [0.1908342 , 0.38890714, 0.42025866],
       [0.22501625, 0.46461061, 0.31037314],
       [0.36304264, 0.59155755, 0.04539982]])

In [3]:
U.shape

(5, 3)

In [2]:
0.29399155+0.33750765+0.1908342+0.22501625+0.36304264

1.4103922899999999

In [4]:
s=0
for i in range(U.shape[0]):
    s+=U[i,0]
s

1.4103922906737678

In [6]:
np.sum(U[:,0])

1.4103922906737678

In [12]:
np.random.seed(0)
matrix = np.random.rand(10, 3)
row_sums = np.sum(matrix, axis=1)
U = matrix / row_sums[:, np.newaxis]
U

sum = 0
for i in range( U.shape[0]):
    sum += (U[i,0]**2) * U[i,:]

sum

array([0.34574825, 0.32473767, 0.26772849])

In [13]:
sum = np.sum((U[:, 0]**2)[:, np.newaxis] * U, axis=0)
tmp=sum/np.sum(U[:,0])

In [14]:
tmp

array([0.12242324, 0.11498377, 0.09479785])

In [15]:
U[0,:]=tmp

In [16]:
U

array([[0.12242324, 0.11498377, 0.09479785],
       [0.33750765, 0.26241723, 0.40007512],
       [0.1908342 , 0.38890714, 0.42025866],
       [0.22501625, 0.46461061, 0.31037314],
       [0.36304264, 0.59155755, 0.04539982],
       [0.09269394, 0.02150968, 0.88579638],
       [0.29623897, 0.3312077 , 0.37255333],
       [0.3915204 , 0.22608603, 0.38239357],
       [0.13119027, 0.70980192, 0.15900781],
       [0.5021685 , 0.2774049 , 0.22042661]])

In [32]:
np.sum((U[:, 0])[:, np.newaxis] , axis=0)

array([2.82420438])